# Generated by Django 3.1.7 on 2021-05-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BendTheTrend', '0004_auto_20210516_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
