# Generated by Django 3.1.7 on 2021-05-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BendTheTrend', '0005_remove_product_digital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('mail', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
