# Generated by Django 3.1.7 on 2021-05-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BendTheTrend', '0006_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mail',
            new_name='email',
        ),
    ]
