# Generated by Django 3.1.7 on 2021-05-19 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0005_auto_20210519_0529'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BendTheTrend', '0007_auto_20210517_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designers.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
