# Generated by Django 3.1.7 on 2021-05-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
