# Generated by Django 3.1.7 on 2021-05-18 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0004_auto_20210518_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['price']},
        ),
    ]
